version: '3.7'

services:
  mongodb:
    image: mongo:8.0.0-rc4
    hostname: ${MONGODB_HOST}
    container_name: ChatAppDB
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    volumes:
      - ./data:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE}
    ports:
      - 27017:27017
    env_file: .env