version: '3'

services:
  mongodb:
    image: mongo:8.0.0-rc4
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
  mongo-client:
    image: mongo-express:1.0.2-20
    container_name: mongo-client
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT}
    ports:
      - 8081:8081
    networks:
      - mongodb_network
volumes:
  mongodb_data:
networks:
  mongodb_network: